version: "3.9"

services:
  omninxt-sim-service:
    image: omninxt-sim
    build:
      context: .
      dockerfile: sim.dockerfile
    restart: no
    privileged: true
    network_mode: host
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES=all
      - FASTRTPS_DEFAULT_PROFILES_FILE=/omninxt-sim/ros_bridge/dds_profile.xml
      - DISPLAY=:$DISPLAY
    volumes:
      - ${OMNINXT_SIM_PATH}:/omninxt-sim
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    entrypoint: ["bash", "-c", "/omninxt-sim/docker/repair_repo.sh && cd /omninxt-sim/PX4-Autopilot && make clean && make px4_sitl_default && source /omninxt-sim/scripts/env.sh && . /isaac-sim/runheadless.native.sh -v"]