version: "3.9"

services:
  omninxt-sim-service:
    image: omninxt-sim
    build:
      context: sim
      dockerfile: sim.dockerfile
      args:
        - USER=${USER}
    restart: no
    depends_on:
      - novnc
    privileged: true
    network_mode: host

    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES=all
      - FASTRTPS_DEFAULT_PROFILES_FILE=/omninxt-sim/ros_bridge/dds_profile.xml
      - DISPLAY=:10.0
    volumes:
      - ${OMNINXT_SIM_PATH}:/omninxt-sim
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    entrypoint: ["bash", "-c", "/omninxt-sim/docker/sim/repair_repo.sh && cd /omninxt-sim/PX4-Autopilot && make px4_sitl_default && source /omninxt-sim/scripts/env.sh && . /isaac-sim/runheadless.native.sh -v"]

  novnc:
    image: novnc
    build:
      context: novnc
      dockerfile: novnc.dockerfile
    restart: no
    # http://<Host>:8080/vnc.html
    # DISPLAY=:1.0
    network_mode: host
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no